### ISSUE TITLE
Performance Issue on Large enums

### ISSUE THREAD

**Issue by anlumo** [illicitonion/num_enum#13]
```Rust
#[derive(TryFromPrimitive)]
```

takes about two minutes on my machine for an enum with ~6700 entries on every compile (even when the module it's in hasn't changed).

With `RUSTFLAGS="-Ztime"` set, the log output shows that the time is spent in the `expand crate` step.

**Comment by illicitonion** [comment]
This has since been fixed in one of our upstream dependencies (`proc-macro2`).

I've just published 0.4.2 of `num_enum` which should use that dependency - if you `cargo update` you should start seeing much better performance :)

Thanks for the bug report, it was an interesting one to dive into, and see others dive into as well, and the fix should hopefully help the wider rust ecosystem!
