### ISSUE TITLE
Also implement `From`/`Into` for reference of enum

### ISSUE THREAD

**Issue by hellow554** [illicitonion/num_enum#3]
One could add `#[derive(Clone, Copy)]` as well on the other hand. Let me know, what you think

**Comment by illicitonion** [comment]
I suspect that adding `#[derive(Copy)]` is the right answer here, rather than to implement `From` and `Into` for references... Is there a reason you don't want to do that, or it's not sufficient for you?

It _does_ pose the interesting question of whether enums with primitive `repr` defined should automatically implement `Copy`... [I've asked on irlo](https://internals.rust-lang.org/t/why-dont-primitive-enums-automatically-implement-copy/10401) to see if maybe we could automatically do that in the language :)

**Comment by illicitonion** [comment]
I'm going to close this as I'd recommend just deriving `Copy`, but feel free to comment/re-open if there are good reasons not to :)
