### ISSUE TITLE
Doc deprecated for try_from

### ISSUE THREAD

**Issue by Chadehoc** [illicitonion/num_enum#47]
The main page documents as `try_from` what now seems to be `try_from_primitive`.

**Comment by illicitonion** [comment]
Thanks for filing this issue! We actually implement both - the derive macro expands an implementation of `TryFrom` [here](https://github.com/illicitonion/num_enum/blob/d0ac4cd13e62d08313e4c8f8fba2ceca113b5ca5/num_enum_derive/src/lib.rs#L561-L571) which itself calls `try_from_primitive` (and is marked `#[inline]`).

As a caller, you can use either, but I'd recommend `try_from` as that's the standard trait (and so can be used in more contexts, e.g. in a function which is generic over a type which implements `TryFrom`), and `try_from_primitive` is more of an implementation detail, which is why this is what the documentation uses `try_from`.

Please re-open this issue if that's not clear, or if there's anything you still think we should change :)

**Comment by Chadehoc** [comment]
Sorry! I had just forgotten the initial "use std::convert::TryFrom;"... And
I think code completion proposed "try_from_primitive", so I thought it had
been replaced (and it worked). I think an experienced rust programmer would
not have been fooled.
