### ISSUE TITLE
Add Apache-2.0/MIT license scheme

### ISSUE THREAD

**Issue by zbraniecki** [illicitonion/num_enum#62]
We recently started using num_enum crate in [ICU4X](https://github.com/unicode-org/icu4x) and encountered a licensing friction point.

We plan to include ICU4X into Gecko and Gecko approves the standard Rust combination of Apache-2.0 and MIT licenses (just like Rust is licensed itself).
Unfortunately, `num_enum` carries with it another license, that we'd now need to also work with lawyers to resolve which creates a friction point for us, and all future users of ICU4X.

We'd like to request addition of Apache-2.0/MIT scheme to your crate to remove this friction point.

**Comment by illicitonion** [comment]
Thanks for filing this issue - it's exciting we can be helpful to ICU4X!

My understanding is that adding MIT as an acceptable licence is trivial, as it doesn't confer new rights that BSD doesn't already cover.

In order to add Apache 2, I believe we'd need agreement for all of our historical contributors. Concretely, I'd propose we allow a choice of BSD, Apache 2, or MIT licence to be used, as much of the Rust community allows. Our aim is to be maximally permissive.

I've attached a list of contributors below - folks, **please can you leave a comment accepting you're happy for your contributions to be released under all of the above licences**. I'm not a lawyer, but I believe the only impact for y'all is that you grant patent use rights to users of this library, specifically for any infringement that results as a direct use of this library.

- [x] @illicitonion 
- [ ] @qoh
- [ ] @rgiot 
- [ ] @TyberiusPrime
- [ ] @danielhenrymantilla 
- [ ] @benesch 
- [ ] @regexident 
- [ ] @jonasmalacofilho

**Comment by regexident** [comment]
I'm happy for my contributions to be released under all of the above licenses! :+1:

**Comment by rgiot** [comment]
No problem (I have to admit that I forget I contributted a little)

**Comment by danielhenrymantilla** [comment]
My contributions in this project can be released under any of the following licenses: BSD, Apache 2, or MIT licence (and, FWIW, I'm generally fine with any contribution I make in any Rust open-source project to be released under Apache 2, MIT, or ZLib licenses).

**Comment by benesch** [comment]
I accept as well!

**Comment by TyberiusPrime** [comment]
Everyone is welcome to use my past contribution to this project under any of those licenses (Apache-2.0, MIT or BSD-3-Clause).

**Comment by illicitonion** [comment]
Having looked through our contribution history, it looks like the only contribution which hasn't been acknowledged above was a pure deletion (for which we're nonetheless incredibly grateful!), so I think we're good to go - I've just pushed https://github.com/illicitonion/num_enum/pull/64 to add the relevant license options, and will kick off a release :)

**Comment by illicitonion** [comment]
0.5.5 is published to crates.io 🎉

**Comment by zbraniecki** [comment]
Thank you!

**Comment by Manishearth** [comment]
Amazing, thank you!
